[project]
name = "shupracticum2025"
version = "0.1.0"
description = "实训报告"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "ipykernel>=6.29.5",
    "networkx>=3.5",
    "nbstripout",
    "scipy>=1.16.2",
]
